apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: haiku
    service: db
  name: haiku-db
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /mnt/primary/iocage/laniakea/haiku-db
    server: 10.0.1.100
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  volumeMode: Filesystem
