apiVersion: v1
kind: Service
metadata:
  labels:
    app: haiku
    service: db
  name: haiku-db
  namespace: haiku
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: haiku
    service: db
  sessionAffinity: None
  type: ClusterIP
